Repository threat9/routersploit, pull requests merged in 2018-08, with the labels that each got.

#494 setup.py improvements and routersploit/resources/ installation via MANIFEST.in
  MANIFEST.in
  routersploit/resources/__init__.py
  setup.py
Labels: enhancement

#501 Fix: Show/Set Payloads issue
  routersploit/core/exploit/shell.py
Labels: bug

#502 Switching to pycryptodome
  requirements-dev.txt
  requirements.txt
  setup.py
Labels: bug, enhancement
