Repository threat9/routersploit, pull requests merged in 2018-09, with the labels that each got.

#504 Updating requirements
  requirements-dev.txt
  requirements.txt
Labels: enhancement

#505 Unifying ftp/ssh/telnet/snmp communication
  routersploit/core/ftp/ftp_client.py
  routersploit/core/snmp/snmp_client.py
  routersploit/core/ssh/ssh_client.py
  routersploit/core/tcp/tcp_client.py
  routersploit/core/telnet/telnet_client.py
  routersploit/core/udp/udp_client.py
  routersploit/modules/creds/generic/ftp_bruteforce.py
  routersploit/modules/creds/generic/ftp_default.py
  routersploit/modules/creds/generic/snmp_bruteforce.py
  routersploit/modules/creds/generic/ssh_bruteforce.py
  routersploit/modules/creds/generic/ssh_default.py
  routersploit/modules/creds/generic/telnet_bruteforce.py
  routersploit/modules/creds/generic/telnet_default.py
  routersploit/modules/creds/routers/mikrotik/api_ros_default_creds.py
  routersploit/modules/exploits/cameras/grandstream/gxv3611hd_ip_camera_backdoor.py
  routersploit/modules/exploits/cameras/grandstream/gxv3611hd_ip_camera_sqli.py
  routersploit/modules/exploits/generic/heartbleed.py
  routersploit/modules/exploits/generic/ssh_auth_keys.py
  routersploit/modules/exploits/routers/cisco/ucm_info_disclosure.py
  routersploit/modules/exploits/routers/dlink/dir_300_645_815_upnp_rce.py
  routersploit/modules/exploits/routers/dlink/dwr_932b_backdoor.py
  routersploit/modules/exploits/routers/huawei/hg520_info_disclosure.py
  routersploit/modules/exploits/routers/mikrotik/routeros_jailbreak.py
  routersploit/modules/exploits/routers/mikrotik/winbox_auth_bypass_creds_disclosure.py
  routersploit/modules/exploits/routers/multi/tcp_32764_info_disclosure.py
  routersploit/modules/exploits/routers/multi/tcp_32764_rce.py
  routersploit/modules/exploits/routers/netcore/udp_53413_rce.py
  routersploit/modules/exploits/routers/technicolor/tg784_authbypass.py
  routersploit/modules/exploits/routers/thomson/twg849_info_disclosure.py
  routersploit/modules/generic/upnp/ssdp_msearch.py
Labels: enhancement

#507 AsusWRT Lan RCE
  docs/modules/exploits/routers/asus/asuswrt_lan_rce.md
  routersploit/modules/exploits/routers/asus/asuswrt_lan_rce.py
  tests/exploits/routers/asus/test_asuswrt_lan_rce.py
Labels: docs, module, tests

#508 Fixing InfoSVR Backdoor RCE module
  docs/modules/exploits/routers/asus/infosvr_backdoor_rce.md
  routersploit/modules/exploits/routers/asus/infosvr_backdoor_rce.py
Labels: bug, docs, module

#509 Add creds from Mirai and sort wordlists
  routersploit/resources/wordlists/defaults.txt
  routersploit/resources/wordlists/passwords.txt
  routersploit/resources/wordlists/usernames.txt
Labels: enhancement

#511 Fixing false positive - 3com officeconnect rce
  routersploit/modules/exploits/routers/3com/officeconnect_rce.py
Labels: bug

#513 Fixing multiple modules
  routersploit/modules/exploits/routers/billion/billion_5200w_rce.py
  routersploit/modules/exploits/routers/cisco/catalyst_2960_rocem.py
  routersploit/modules/exploits/routers/cisco/firepower_management60_rce.py
  routersploit/modules/exploits/routers/dlink/dir_815_850l_rce.py
  routersploit/modules/exploits/routers/multi/tcp_32764_rce.py
  routersploit/modules/exploits/routers/ubiquiti/airos_6_x.py
  tests/exploits/routers/multi/test_tcp_32764_rce.py
Labels: bug

#515 Fixing options
  routersploit/core/exploit/option.py
  routersploit/interpreter.py
  routersploit/modules/payloads/perl/bind_tcp.py
  routersploit/modules/payloads/perl/reverse_tcp.py
  routersploit/modules/payloads/php/bind_tcp.py
  routersploit/modules/payloads/php/reverse_tcp.py
  routersploit/modules/payloads/python/bind_tcp.py
  routersploit/modules/payloads/python/bind_udp.py
  routersploit/modules/payloads/python/reverse_tcp.py
  routersploit/modules/payloads/python/reverse_udp.py
  tests/core/__init__.py
  tests/core/test_option.py
Labels: enhancement, tests

#517 Requirements - Setting pysnmp version
  requirements-dev.txt
  requirements.txt
Labels: bug

#519 Fixing use command issue
  routersploit/core/exploit/utils.py
Labels: bug

#520 Adding tests for Cisco Video Surveillance Path Traversal module
  routersploit/modules/exploits/cameras/cisco/__init__.py
  routersploit/modules/exploits/cameras/cisco/video_surv_path_traversal.py
  tests/exploits/cameras/cisco/__init__.py
  tests/exploits/cameras/cisco/test_video_surv_path_traversal.py
Labels: tests
