Repository threat9/routersploit, pull requests merged in 2018-06, with the labels that each got.

#446 Adding SSDP MSEARCH module
  docs/modules/generic/upnp/ssdp_msearch.md
  routersploit/modules/generic/upnp/__init__.py
  routersploit/modules/generic/upnp/ssdp_msearch.py
Labels: docs, module

#447 Fixing TCP-32764 modules, adding tests and docs
  docs/modules/exploits/routers/multi/tcp_32764_info_disclosure.md
  docs/modules/exploits/routers/multi/tcp_32764_rce.md
  routersploit/modules/exploits/routers/multi/tcp_32764_info_disclosure.py
  routersploit/modules/exploits/routers/multi/tcp_32764_rce.py
  tests/conftest.py
  tests/exploits/routers/multi/test_tcp_32764_info_disclosure.py
  tests/exploits/routers/multi/test_tcp_32764_rce.py
Labels: docs, module, tests

#448 Improving PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#449 Update README.md
  README.md
Labels: enhancement

#451 TCP & UDP based exploits
  routersploit/modules/creds/routers/mikrotik/api_ros_default_creds.py
  routersploit/modules/exploits/routers/cisco/catalyst_2960_rocem.py
  routersploit/modules/exploits/routers/dlink/dir_300_645_815_upnp_rce.py
  routersploit/modules/exploits/routers/dlink/dir_815_850l_rce.py
  routersploit/modules/exploits/routers/dlink/dwr_932b_backdoor.py
  routersploit/modules/exploits/routers/huawei/hg520_info_dislosure.py
  routersploit/modules/exploits/routers/netcore/udp_53413_rce.py
  tests/creds/routers/mikrotik/test_api_ros_default_creds.py
Labels: bug, enhancement

#454 Adding bind and reverse shell payloads for x86 architecture
  docs/modules/payloads/x86/bind_tcp.md
  docs/modules/payloads/x86/reverse_tcp.md
  routersploit/core/exploit/payloads.py
  routersploit/modules/payloads/x86/__init__.py
  routersploit/modules/payloads/x86/bind_tcp.py
  routersploit/modules/payloads/x86/reverse_tcp.py
  tests/payloads/__init__.py
  tests/payloads/x86/__init__.py
  tests/payloads/x86/test_bind_tcp.py
  tests/payloads/x86/test_reverse_tcp.py
Labels: docs, module, tests

#455 Payloads x64
  docs/modules/payloads/x64/bind_tcp.md
  docs/modules/payloads/x64/reverse_tcp.md
  routersploit/core/exploit/payloads.py
  routersploit/modules/payloads/x64/__init__.py
  routersploit/modules/payloads/x64/bind_tcp.py
  routersploit/modules/payloads/x64/reverse_tcp.py
  tests/payloads/x64/__init__.py
  tests/payloads/x64/test_bind_tcp.py
  tests/payloads/x64/test_reverse_tcp.py
Labels: docs, module, tests

#457 Adding Python UDP Bind Shell
  docs/modules/payloads/cmd/python_bind_udp.md
  docs/modules/payloads/python/bind_udp.md
  routersploit/modules/payloads/cmd/python_bind_udp.py
  routersploit/modules/payloads/python/bind_udp.py
  tests/payloads/cmd/__init__.py
  tests/payloads/cmd/test_python_bind_udp.py
  tests/payloads/python/__init__.py
  tests/payloads/python/test_bind_udp.py
Labels: docs, module, tests

#458 Adding Python UDP Reverse Shell payloads
  docs/modules/payloads/cmd/python_reverse_udp.md
  docs/modules/payloads/python/reverse_udp.md
  routersploit/modules/payloads/cmd/python_reverse_udp.py
  routersploit/modules/payloads/python/reverse_udp.py
  tests/payloads/cmd/test_python_reverse_udp.py
  tests/payloads/python/test_reverse_udp.py
Labels: docs, module, tests

#459 Adding PHP Bind TCP payloads
  docs/modules/payloads/cmd/php_bind_tcp.md
  docs/modules/payloads/php/bind_tcp.md
  routersploit/modules/payloads/cmd/php_bind_tcp.py
  routersploit/modules/payloads/php/bind_tcp.py
  tests/payloads/cmd/test_php_bind_tcp.py
  tests/payloads/php/__init__.py
  tests/payloads/php/test_bind_tcp.py
Labels: docs, module, tests

#460 AWK UDP Bind Shell Payload
  docs/modules/payloads/cmd/awk_bind_udp.md
  routersploit/modules/payloads/cmd/awk_bind_udp.py
  tests/payloads/cmd/test_awk_bind_udp.py
Labels: docs, module, tests

#465 Fixing boolean options
  routersploit/core/exploit/option.py
  routersploit/core/ftp/ftp_client.py
  routersploit/core/http/http_client.py
  routersploit/core/snmp/snmp_client.py
  routersploit/core/ssh/ssh_client.py
  routersploit/core/tcp/tcp_client.py
  routersploit/core/telnet/telnet_client.py
  routersploit/core/udp/udp_client.py
  routersploit/modules/creds/cameras/acti/webinterface_http_form_default_creds.py
  routersploit/modules/creds/cameras/basler/webinterface_http_form_default_creds.py
  routersploit/modules/creds/generic/ftp_bruteforce.py
  routersploit/modules/creds/generic/ftp_default.py
  routersploit/modules/creds/generic/http_basic_digest_bruteforce.py
  routersploit/modules/creds/generic/http_basic_digest_default.py
  routersploit/modules/creds/generic/snmp_bruteforce.py
  routersploit/modules/creds/generic/ssh_bruteforce.py
  routersploit/modules/creds/generic/ssh_default.py
  routersploit/modules/creds/generic/telnet_bruteforce.py
  routersploit/modules/creds/generic/telnet_default.py
  routersploit/modules/creds/routers/mikrotik/api_ros_default_creds.py
  routersploit/modules/creds/routers/pfsense/webinterface_http_form_default_creds.py
  routersploit/modules/exploits/routers/cisco/firepower_management60_rce.py
  routersploit/modules/exploits/routers/cisco/secure_acs_bypass.py
  routersploit/modules/exploits/routers/ipfire/ipfire_oinkcode_rce.py
  routersploit/modules/exploits/routers/thomson/twg849_info_disclosure.py
  routersploit/modules/exploits/routers/ubiquiti/airos_6_x.py
  routersploit/modules/exploits/routers/zyxel/zywall_usg_extract_hashes.py
  routersploit/modules/generic/bluetooth/btle_scan.py
  routersploit/modules/generic/bluetooth/btle_write.py
  routersploit/modules/scanners/autopwn.py
Labels: enhancement

#466 Fixing telnet read until
  routersploit/core/telnet/telnet_client.py
Labels: bug

#444 Python package configuration - setuptools
  setup.py
Labels: enhancement

#468 Tests for UDP-based exploits
  routersploit/core/udp/udp_client.py
  routersploit/modules/creds/generic/snmp_bruteforce.py
  routersploit/modules/exploits/routers/cisco/ucm_info_disclosure.py
  routersploit/modules/exploits/routers/dlink/dir_300_645_815_upnp_rce.py
  routersploit/modules/exploits/routers/dlink/dir_815_850l_rce.py
  routersploit/modules/exploits/routers/dlink/dwr_932b_backdoor.py
  routersploit/modules/exploits/routers/huawei/hg520_info_disclosure.py
  routersploit/modules/exploits/routers/netcore/udp_53413_rce.py
  routersploit/modules/generic/upnp/ssdp_msearch.py
  tests/conftest.py
  tests/exploits/routers/cisco/test_ucm_info_disclosure.py
  tests/exploits/routers/dlink/test_dir_300_645_815_upnp_rce.py
  tests/exploits/routers/dlink/test_dir_815_850l_rce.py
  tests/exploits/routers/dlink/test_dwr_932b_backdoor.py
  tests/exploits/routers/huawei/test_hg520_info_disclosure.py
  tests/exploits/routers/netcore/__init__.py
  tests/exploits/routers/netcore/test_udp_53413_rce.py
  tests/generic/__init__.py
  tests/generic/upnp/test_ssdp_msearch.py
Labels: tests

#469 Fixed false positive issue #305 in version 3.1.0
  routersploit/modules/exploits/routers/zte/zxv10_rce.py
Labels: bug

#471 Fixing heartbleed exploit
  routersploit/modules/exploits/generic/heartbleed.py
Labels: bug

#475 Fixing ISSUE TEMPLATE
  .github/ISSUE_TEMPLATE.md
Labels: enhancement

#477 Bump v3.2.0
  routersploit/interpreter.py
  setup.py
Labels: release

#478 Improve TCP communication
  routersploit/core/tcp/tcp_client.py
  routersploit/modules/exploits/generic/heartbleed.py
Labels: enhancement
