Repository threat9/routersploit, pull requests merged in 2024-04, with the labels that each got.

#765 Added another Zyxel default variant
  routersploit/modules/creds/routers/zyxel/ftp_default_creds.py
  routersploit/modules/creds/routers/zyxel/ssh_default_creds.py
  routersploit/modules/creds/routers/zyxel/telnet_default_creds.py
  routersploit/resources/wordlists/defaults.txt
  routersploit/resources/wordlists/passwords.txt
  tests/creds/routers/zyxel/test_ftp_default_creds.py
  tests/creds/routers/zyxel/test_ssh_default_creds.py
  tests/creds/routers/zyxel/test_telnet_default_creds.py
Labels: enhancement

#754 Update autopwn.py
  routersploit/modules/scanners/autopwn.py
Labels: enhancement

#815 fix info issue p2p wificam rce exploit
  routersploit/modules/exploits/cameras/multi/P2P_wificam_rce.py
Labels: bug

#816 Fix Mikrotik RouterOS API creds module
  routersploit/libs/apiros/apiros_client.py
  routersploit/modules/creds/routers/mikrotik/api_ros_default_creds.py
Labels: bug

#473 Create hg532_rce.py
  routersploit/modules/exploits/routers/huawei/hg532_rce.py
Labels: module, needs-tests, needs-docs

#817 Fix HG532 RCE exploit module
  routersploit/modules/exploits/routers/huawei/hg532_rce.py
Labels: bug

#818 Fix printer
  routersploit/core/exploit/printer.py
Labels: bug

#689 Fix exploit check for routers/linksys/test_eseries_themoon_rce.
  routersploit/modules/exploits/routers/linksys/eseries_themoon_rce.py
  tests/exploits/routers/linksys/test_eseries_themoon_rce.py
Labels: bug

#768 Add a password reset module for TP-Link Archer routers (CVE-2017-11519)
  routersploit/modules/exploits/routers/tplink/archer_c9_admin_password_reset.py
Labels: module
